In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv('heart_failure_clinical_records_dataset.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, 12].values

In [3]:
X=X[:, 1:]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

c:\users\angshuman\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [7]:
y_pred=classifier.predict(X_test)

In [8]:
print(y_pred)

[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0]


In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [10]:
print(cm)

[[35  2]
 [12 11]]


In [17]:
# 46 out 60 data are giving accurate results if we use Logistic Regression  ; Accuracy = 76.66%

In [13]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
classifier_2=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier_2.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [14]:
y_pred_2=classifier_2.predict(X_test)

In [15]:
cm_2=confusion_matrix(y_test,y_pred_2)

In [16]:
print(cm_2)

[[31  6]
 [ 6 17]]


In [18]:
# 48 out of 60 test data are giving accurate results if we use Decision Tree ; Accuracy = 80% 

In [19]:
from sklearn.naive_bayes import GaussianNB
classifier_3=GaussianNB()
classifier_3.fit(X_train,y_train)

GaussianNB()

In [20]:
y_pred_3=classifier_3.predict(X_test)

In [21]:
cm_3=confusion_matrix(y_test,y_pred_3)

In [22]:
print(cm_3)

[[36  1]
 [15  8]]


In [23]:
# 44 out of 60 test data are giving accurate results if we use Decision Tree ; Accuracy = 73.33% 

In [24]:
# So , Decision Tree Classifier is most suitable for this dataset .